### ANGGA NURWAHYU UTOMO
### A11.2022.14575

### Import Library

In [234]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### Import Dataset

In [235]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [236]:
print(X)

[['Malaysia' 23.0 45000.0]
 ['Japan' 54.0 28000.0]
 ['Malaysia' nan 69000.0]
 ['China' 70.0 nan]
 ['German' 80.0 99000.0]
 ['China' nan 30000.0]
 ['Korea' 55.0 82000.0]
 ['Japan' 12.0 12000.0]
 ['China' 77.0 nan]
 ['Ukraina' 41.0 89000.0]]


In [237]:
print(Y)

['Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No']


### 1. Menghilangkan Missing Value (nan)

In [238]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [239]:
print(X)

[['Malaysia' 23.0 45000.0]
 ['Japan' 54.0 28000.0]
 ['Malaysia' 51.5 69000.0]
 ['China' 70.0 56750.0]
 ['German' 80.0 99000.0]
 ['China' 51.5 30000.0]
 ['Korea' 55.0 82000.0]
 ['Japan' 12.0 12000.0]
 ['China' 77.0 56750.0]
 ['Ukraina' 41.0 89000.0]]


### 2. Encoding Data Kategori (Atribut)

In [240]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[('encoder', OneHotEncoder (), [0])], remainder= 'passthrough')
X = np. array(ct.fit_transform(X))

In [241]:
print(X)

[[0.0 0.0 0.0 0.0 1.0 0.0 23.0 45000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 54.0 28000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 51.5 69000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 70.0 56750.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 80.0 99000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 51.5 30000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 55.0 82000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 12.0 12000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 77.0 56750.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 41.0 89000.0]]


### 3. Encoding Data Kategori (Class/Label)

In [242]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder ()
Y = le.fit_transform (Y)

In [243]:
print(Y)

[1 0 0 1 1 1 1 1 0 0]


### 4. Membagi Dataset ke dalam Training Set dan Test Set

In [244]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [245]:
print(X_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 55.0 82000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 80.0 99000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 23.0 45000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 70.0 56750.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 54.0 28000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 12.0 12000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 77.0 56750.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 51.5 30000.0]]


In [246]:
print(Y_train)

[1 1 1 1 0 1 0 1]


In [247]:
print(X_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 51.5 69000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 41.0 89000.0]]


In [248]:
print(Y_test)

[0 0]


### 5. Feature Scaling

In [249]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [250]:
print(X_train)

[[0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 0.0
  0.09567592365379686 1.1386835285450903]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  1.1891150511257609 1.7669227167078987]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 0.0
  -1.303926159510317 -0.22866058686808102]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  0.7517394001369753 0.20556355789150718]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 0.0
  0.051938358554918296 -0.8568997750308894]
 [0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 0.0
  -1.7850393755979814 -1.4481837168311797]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  1.0579023558291252 0.20556355789150718]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0
  -0.057405554192278115 -0.7829892823058532]]


In [251]:
print(X_test)

[[0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 0.0
  -0.057405554192278115 0.6582653258323544]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.0
  -0.5166499877305031 1.3973702530827175]]
